const SHOW_LOGIN_VIEW = 'SHOW_LOGIN_VIEW';
const SHOW_LOGIN_BG = 'SHOW_LOGIN_BG';
const SHOW_PAY_VIEW = 'SHOW_PAY_VIEW';
const SHOW_GAME = 'SHOW_GAME';
const SHOW_FLOAT_ICON = 'SHOW_FLOAT_ICON';
const SHOW_USER_PROFILE = 'SHOW_USER_PROFILE';

const SET_CURRENT_USER = 'SET_CURRENT_USER';
const UNSET_CURRENT_USER = 'UNSET_CURRENT_USER';
const USER_ACCOUNT_LIST = 'USER_ACCOUNT_LIST';

const PAY_INFO = 'PAY_INFO';

export default {
    SHOW_LOGIN_VIEW,
    SHOW_LOGIN_BG,
    SHOW_PAY_VIEW,
    SHOW_GAME,
    SHOW_FLOAT_ICON,
    SHOW_USER_PROFILE,
    SET_CURRENT_USER,
    UNSET_CURRENT_USER,
    USER_ACCOUNT_LIST,
    PAY_INFO
}


// WEBPACK FOOTER //
// ./src/store/actions/ActionTypes.js